name: Fetch Huizemark Stock (nightly, debug)

on:
  schedule:
    # every day at 02:15 UTC
    - cron: "15 2 * * *"
  workflow_dispatch: {}   # manual Run button
  push:
    paths:
      - "scripts/fetch_stock.py"
      - ".github/workflows/fetch-listings.yml"

permissions:
  contents: write  # allow committing data/listings.json back to repo

jobs:
  update-listings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree (quick sanity)
        run: |
          pwd
          ls -la
          echo "-----"
          ls -la data || true
          echo "-----"
          ls -la scripts || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml html5lib

      - name: Verify imports (fast fail if missing)
        run: |
          python - << 'PY'
          try:
              import requests, bs4, lxml, html5lib
              print("✅ imports OK")
          except Exception as e:
              print("❌ import failed:", e)
              raise
          PY

      - name: Quick network check (agent page)
        run: |
          curl -I --location --max-time 20 "https://www.huizemark.com/agents/blessing-nsibande/75570/" || true
          curl -I --location --max-time 20 "https://www.huizemark.com/results/agent/75570/" || true

      - name: Run fetch_stock.py (agent 75570)
        id: fetch
        run: |
          set -e
          python --version
          python scripts/fetch_stock.py
          echo "----- data dir after run -----"
          ls -la data || true

      - name: Show git diff (what changed)
        run: |
          git status
          git diff --stat || true

      - name: Commit changes (if any)
  shell: bash
  run: |
    set -euo pipefail

    git config user.name  "smartmatch-bot"
    git config user.email "bot@users.noreply.github.com"

    # Stage files only if they exist
    [ -f data/listings.json ] && git add data/listings.json
    [ -f debug_skipped.json ] && git add debug_skipped.json
    [ -f canva/bulk_create.csv ] && git add canva/bulk_create.csv
    [ -f canva/bulk_create.json ] && git add canva/bulk_create.json
    [ -f sitemap.xml ] && git add sitemap.xml

    # Commit only if something is staged
    if git diff --cached --quiet; then
      echo "No changes to commit."
    else
      git commit -m "Auto-update listings.json (agent 75570)"
      git push
    fi


      - name: Upload artifacts (inspect if failure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smartmatch-artifacts
          path: |
            data/listings.json
            debug_skipped.json
          if-no-files-found: warn
