name: Fetch Huizemark Stock (nightly)

on:
  schedule:
    - cron: "15 2 * * *"   # daily 02:15 UTC
  workflow_dispatch: {}     # manual run button
  push:
    paths:
      - "scripts/fetch_stock.py"
      - ".github/workflows/fetch-listings.yml"

permissions:
  contents: write            # allow committing back to the repo

jobs:
  update-listings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show tree (optional)
        run: |
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y tree >/dev/null
          tree -L 2 || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml html5lib

      - name: Run fetch_stock.py (agent 75570 only)
        run: |
          python scripts/fetch_stock.py

      - name: Commit changes (if any)
        shell: bash
        run: |
          set -euo pipefail

          git config user.name  "smartmatch-bot"
          git config user.email "bot@users.noreply.github.com"

          # Stage files only if they exist
          [[ -f data/listings.json       ]] && git add data/listings.json || true
          [[ -f debug_skipped.json       ]] && git add debug_skipped.json || true
          [[ -f canva/bulk_create.csv    ]] && git add canva/bulk_create.csv || true
          [[ -f canva/bulk_create.json   ]] && git add canva/bulk_create.json || true
          [[ -f sitemap.xml              ]] && git add sitemap.xml || true

          # Commit only if something is staged
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update listings.json (agent 75570)"
            git push
          fi
